### PR TITLE
Change parsing explicit loung double constants

### PR DESCRIPTION
**Pull request by Dudeldu**
In relation to PR #11, I tried to use DBL_MAX with the code from this PR, and I ended up with the following test code:

```c
// PARAM: --enable ana.float.interval --enable warn.float
#include <float.h>

void main()
{
    int check1 = (0.2 == 0.2); // WARN
    int check2 = (0.2 != 0.3); // WARN

    // The following is __DBL_MAX__
    double my_max = 1.79769313486231570814527423731704357e+308;
    double my_max2 = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000;
    printf("%f\n", my_max);
    printf("%f\n", DBL_MAX);

    // As numbers this big cannot be represented exactly anymore by double, this "- 1" will get
    // completely consumed.
    double max_minus_one = my_max - 1; // WARN
    double x1 = my_max2 - 1; // WARN
    double x2 = DBL_MAX - 1; // WARN
}

```

This resulted in very strange errors:

- For `x2`, we got at that line a warning that the operation is not exact.
- We didn't get this for neither `x1` nor `max_minus_one`, even though we would expect it there as well

### CODE REVIEW

**Review by FelixKrayer — DISMISSED** [review]

**Comment by Dudeldu** [comment]
It seems like this solution is for now working with DBL_MIN/DBL_MAX (at least locally on may machine but fails on the github action servers). 
Another problem where i still did not find the root cause for, is that using the numbers without an explicit L for indicating, that those are long doubles, the tests fail, without any warning. It seems like we are able to compute `1.7976931348623157e+308 + 1.` without loss of precision, which would be great... but is not possible...

**Comment by Dudeldu** [comment]
Another thing i have discovered during searching for a solution is, that `DBL_MAX` (similar things apply to `DBL_MIN` as well) is defined as "at least" `1e+37` which means, that it can actually differ between platforms. The perfect sound solution therefore would be to just use this value. However i think this is pretty pessimistic and i would rather sacrifice the soundness instead of precision in this case... However this maybe means we should pick reasonable constants for DBL_MAX instead of taking the actual C values as those could be platform dependent (this also implies that we will not be able to run on machines with lower DBL_MAX than expected). If we did so, we also had to change the "detection" of this special values again or somehow generally allow long doubles only in places followed by an immediate double cast, so we can directly treat it as a double...
@FelixKrayer @brgr Opinions on that?

**Comment by Dudeldu** [comment]
Another implication from what i mentioned above, and from what we see in the failing regression tests, is that with this restricted implementation it can happen, that double max is not necessarily representable in our domain... (it is yet to be determined, if this actually already happens inside cil or within our domain). May this can be checked by one of you, because i can't reproduce the failing regression tests locally.

**Comment by FelixKrayer** [comment]
> Another implication from what i mentioned above, and from what we see in the failing regression tests, is that with this restricted implementation it can happen, that double max is not necessarily representable in our domain... (it is yet to be determined, if this actually already happens inside cil or within our domain). May this can be checked by one of you, because i can't reproduce the failing regression tests locally.

I am quite positive that this is a Problem within CIL, not in goblint. I checked, and the `num` which the line `| CastE (TFloat ((FFloat | FDouble as fkind), _), Const (CReal (num, FLongDouble, _))) -> 'Float (FD.of_const fkind num)` receives is already `inf` for DBL_MAX (~`2.22507e-308` for DBL_MIN which is fine). 
Also in CIL `cabs2cil.ml` line 3624 the parsing of input occurs (the text "treating long double constant _ as double constant at ..." is printed here). I assume here we get the `inf` for DBL_MAX, even though I am unable to find the `float_of_sting` function that should be responsible here

**Comment by FelixKrayer** [comment]
> Another thing i have discovered during searching for a solution is, that `DBL_MAX` (similar things apply to `DBL_MIN` as well) is defined as "at least" `1e+37` which means, that it can actually differ between platforms. The perfect sound solution therefore would be to just use this value. However i think this is pretty pessimistic and i would rather sacrifice the soundness instead of precision in this case... However this maybe means we should pick reasonable constants for DBL_MAX instead of taking the actual C values as those could be platform dependent (this also implies that we will not be able to run on machines with lower DBL_MAX than expected). If we did so, we also had to change the "detection" of this special values again or somehow generally allow long doubles only in places followed by an immediate double cast, so we can directly treat it as a double... @FelixKrayer @brgr Opinions on that?

Maybe it's best to ask Michael and Julian which they prefer here for Goblint? The same question then extends to the handling  of M_PI, which also strictly speaking is not defined
I personally would say that Soundness is most important over anything.

**Pull request closed without merging**
